apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-k
  namespace: squidgame
  labels:
    app: grpc-k
spec:
  selector:
    matchLabels:
      app: grpc-k
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-k
    spec:
      hostname: grpc-pod-host-k
      containers:
        - name: grpc-client-api
          image: sergiounix/client-node_fase2
          env:
          - name: HOST
            value: grpc-pod-host-k
          ports:
            - containerPort: 2000
        - name: grpc-server
          image: sergiounix/server-go_fase2
          env:
          - name: TOPIC
            value: my-topic
          - name: KAFKA_BROKER
            value: my-cluster-kafka-bootstrap.kafka
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-k
  name: svc-grpc-kafka
  namespace: squidgame
spec:
  type: ClusterIP
  selector:
    app: grpc-k
  ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP